// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKFcTb09a82HVqTUF7RMAyiTnZBtYNhIY',
    appId: '1:612594958712:web:80d0f1cd4470cb5a9a888d',
    messagingSenderId: '612594958712',
    projectId: 'cinezone-app',
    authDomain: 'cinezone-app.firebaseapp.com',
    storageBucket: 'cinezone-app.firebasestorage.app',
    measurementId: 'G-7TQMCWXW8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqtgWi5hCb6DCiZPjC3ld5t1K0qpsXClc',
    appId: '1:612594958712:android:4d20392d9e6e83839a888d',
    messagingSenderId: '612594958712',
    projectId: 'cinezone-app',
    storageBucket: 'cinezone-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_MDcBX3K4GV4ehL-TgJns3Le3awfpMtA',
    appId: '1:612594958712:ios:4c0ab13fd368e8659a888d',
    messagingSenderId: '612594958712',
    projectId: 'cinezone-app',
    storageBucket: 'cinezone-app.firebasestorage.app',
    iosBundleId: 'com.example.cinezoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_MDcBX3K4GV4ehL-TgJns3Le3awfpMtA',
    appId: '1:612594958712:ios:4c0ab13fd368e8659a888d',
    messagingSenderId: '612594958712',
    projectId: 'cinezone-app',
    storageBucket: 'cinezone-app.firebasestorage.app',
    iosBundleId: 'com.example.cinezoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKFcTb09a82HVqTUF7RMAyiTnZBtYNhIY',
    appId: '1:612594958712:web:f3e926fc969584d69a888d',
    messagingSenderId: '612594958712',
    projectId: 'cinezone-app',
    authDomain: 'cinezone-app.firebaseapp.com',
    storageBucket: 'cinezone-app.firebasestorage.app',
    measurementId: 'G-H9KXF32CDK',
  );
}
